import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

export const translations = {
  en: {
    nav: {
      tagline: 'Emergency Dispatch',
      liveGrid: '24/7 Live Hospital Grid Active',
      helpline: 'Helpline 108',
      reportEmergency: 'Report Emergency',
      langLabel: 'Language',
      en: 'English (EN)',
      hi: 'हिन्दी (HI)',
      mr: 'मराठी (MR)'
    },
    home: {
      heroBadge: 'Real-Time Emergency Decision Engine',
      heroTitle1: 'Find the ',
      heroTitleRight: 'right',
      heroTitle2: ' hospital.',
      heroTitle3: 'Not just the ',
      heroTitleNearest: 'nearest',
      heroTitle4: ' one.',
      heroDesc: 'In critical emergencies like heart attacks, stroke, or accidents, reaching the closest hospital is useless if they have no open ICU beds or the right specialist. HLERS finds you the fastest hospital with ready doctors and open beds.',
      reportBtn: 'Report Emergency Now',
      howItWorksBtn: 'How It Works',
      speedVal: '< 30s',
      speedLbl: 'Decision Speed',
      bedVal: 'Live',
      bedLbl: 'Bed Tracking',
      trafficVal: '100%',
      trafficLbl: 'Traffic-Aware',
      simTitle: 'LIVE MULTI-HOSPITAL ROUTING',
      cardiac: 'HEART ATTACK',
      stroke: 'STROKE / BRAIN',
      trauma: 'ACCIDENT / INJURY',
      burns: 'BURN EMERGENCY',
      yourLocation: 'Your Location',
      cardiacName: 'Heart & ICU Center',
      strokeName: 'Brain & Stroke Bay',
      traumaName: 'Trauma Emergency Hub',
      burnsName: 'Specialized Burn Unit',
      driveDuration: 'DRIVE DURATION',
      icuBeds: 'ICU BEDS',
      doctorStatus: 'DOCTOR STATUS',
      comparisonKicker: 'THE CRITICAL DIFFERENCE',
      comparisonHeading: 'Why Regular Maps Are Not Enough in Emergencies',
      comparisonSubtext: 'Driving to the closest building without knowing if they have beds causes fatal delays.',
      legacyStatus: 'REGULAR MAP APPS',
      legacySub: 'Nearest Location Only',
      legacyTitle: 'The "Closest Building" Problem',
      legacyDesc: 'Regular maps guide you only by distance and know nothing about hospital readiness.',
      drivingTime: 'Driving Time:',
      legacyDrive: '4 Mins (Closest)',
      legacyBeds: '0 Beds (Hospital Full)',
      specialist: 'Specialist:',
      legacySpec: 'Doctor Not Available',
      legacyOutcome: 'Danger: Patient is turned away and must find another hospital (20+ mins lost)',
      legacyLi1: 'No way of checking bed capacity before you drive',
      legacyLi2: 'No pre-alert sent to doctors before you arrive',
      hlersStatus: 'HLERS EMERGENCY SYSTEM',
      hlersSub: 'Ready & Capable',
      hlersTitle: 'The "Ready & Capable" Solution',
      hlersDesc: 'Finds the fastest hospital that actually has open beds and the right doctors on duty.',
      hlersDrive: '6 Mins (Live Traffic)',
      hlersBeds: '4 Open Beds Guaranteed',
      hlersSpec: 'Doctor Alerted & Ready',
      hlersOutcome: 'Result: Immediate treatment upon arrival with zero wasted time',
      hlersLi1: 'Direct alert sent to the emergency room desk',
      hlersLi2: 'Turn-by-turn live navigation directly to emergency gates',
      bentoKicker: 'THREE PROTECTIONS IN EVERY EMERGENCY',
      bentoHeading: 'How HLERS Finds Your Best Hospital',
      bentoSubtext: 'We check three critical life-saving factors in real time before recommending any facility.',
      step1Tag: 'STEP 1 · TRAFFIC NAVIGATION',
      step1Badge: 'Live Maps Sync',
      step1Title: 'Fastest Route With Live Traffic',
      step1Desc: 'Calculates the quickest driving route to every nearby hospital using live Google Maps traffic so you avoid roadblocks and traffic jams.',
      step1Analysis: 'Live Traffic Analysis:',
      step1Avoids: 'Avoids Roadblocks',
      step1Instant: 'Instant Routing',
      step2Tag: 'STEP 2 · BED AVAILABILITY',
      step2Badge: 'Real-Time',
      step2Title: 'Guarantees Open ICU Beds',
      step2Desc: 'Checks available intensive care beds and emergency equipment before you travel, so you never arrive at a full hospital.',
      step2MeterHeader: 'Emergency ICU Capacity',
      step2Verified: 'Verified Open',
      step2MeterFooter1: '4 Critical Care Beds Ready',
      step2MeterFooter2: 'Available',
      step3Tag: 'STEP 3 · DOCTOR READINESS',
      step3Badge: 'On Duty',
      step3Title: 'Ensures the Right Doctor Is There',
      step3Desc: 'Confirms that heart doctors, brain specialists, or trauma surgeons are actively on duty and ready to treat the patient immediately.',
      docHeart: 'Heart Specialist',
      docBrain: 'Brain & Stroke Doctor',
      docTrauma: 'Trauma Surgeon',
      docReady: 'Ready',
      docOnDuty: 'On Duty',
      footerBrandSub: 'HyperLocal Emergency Routing System',
      footerMission: 'Intelligent emergency dispatch connecting patients to capable hospitals with live ICU beds and on-duty specialists.',
      footerHubsOnline: 'All Regional Hospital Hubs Online',
      footerTriageHeading: 'Emergency Triage',
      footerHowItWorksHeading: 'How It Works',
      footerHotlinesHeading: 'Emergency Hotlines',
      hotlineNational: 'National Medical Emergency',
      hotlinePolice: 'Police Emergency',
      footerNotice: 'Notice:',
      footerNoticeText: 'HLERS is a decision support tool. For life-threatening emergencies needing immediate ambulance support, always call 108 immediately.',
      footerCopyright: '© HLERS. Built for instant emergency access.'
    },
    emergencyForm: {
      headerTitle: 'EMERGENCY TRIAGE DISPATCH',
      headerSub: 'Instant condition assessment routing to hospitals with verified beds and ready specialists.',
      gpsLocating: 'Scanning GPS Coordinates...',
      gpsLocked: 'GPS Location Locked (Accuracy ±5m)',
      step1Title: '1. Select Patient Emergency Condition',
      step2Title: '2. Select Severity Level',
      step3Title: '3. Confirm Patient Location',
      condCardiacTitle: 'Heart Attack / Cardiac',
      condCardiacDesc: 'Chest pain, shortness of breath, sudden collapse',
      condStrokeTitle: 'Stroke / Brain Injury',
      condStrokeDesc: 'Facial droop, arm weakness, speech difficulty',
      condTraumaTitle: 'Severe Accident / Trauma',
      condTraumaDesc: 'Deep trauma, heavy bleeding, fractures, vehicle crash',
      condBurnsTitle: 'Severe Burns',
      condBurnsDesc: 'Thermal, chemical, electrical burn injuries',
      condGeneralTitle: 'General Critical Emergency',
      condGeneralDesc: 'Unconscious, breathing failure, severe allergic reaction',
      sevCritical: 'CRITICAL / LIFE-THREATENING',
      sevSevere: 'SEVERE / URGENT',
      sevModerate: 'MODERATE / STABLE',
      locPlaceholder: 'Enter current location, landmark or address',
      findBtn: 'Find Capable Hospitals Now',
      findingBtn: 'Calculating Live Traffic & ICU Beds...'
    },
    hospitalList: {
      triageTitle: 'EMERGENCY DISPATCH RESULTS',
      triageSub: 'Ranked by live driving traffic, confirmed open ICU beds, and specialist readiness.',
      sortFastest: 'Fastest Travel Time',
      sortBeds: 'Most Open Beds',
      sortBest: 'Best Medical Match',
      verifiedReady: 'VERIFIED READY',
      bedsAvailable: 'ICU Beds Available',
      specialistOnDuty: 'Specialist On Duty',
      distanceAway: 'away',
      directAlertBtn: 'Send Pre-Arrival ER Alert',
      alertSentBtn: 'Alert Delivered to ER Desk',
      viewMap: 'View Route & Live Gates',
      callDesk: 'Call ER Desk'
    },
    alertConfirm: {
      alertSuccessTitle: 'EMERGENCY ALERT DELIVERED',
      alertSuccessSub: 'The emergency room at your destination hospital has been notified of your incoming arrival.',
      etaLabel: 'Estimated Time of Arrival',
      hospitalLabel: 'Destination Hospital',
      conditionLabel: 'Patient Emergency',
      bedStatusLabel: 'Reserved ICU Bed',
      docStatusLabel: 'Assigned Specialist',
      checklistTitle: 'Pre-Arrival Action Checklist',
      check1: 'Keep patient calm and avoid sudden movements',
      check2: 'Ensure access route is clear for emergency vehicle',
      check3: 'Keep patient identification and medical history ready',
      check4: 'Follow turn-by-turn navigation directly to Emergency Entrance Gate',
      startNavBtn: 'Start Live GPS Turn-by-Turn Navigation',
      cancelAlertBtn: 'Modify / Cancel Alert'
    },
    notFound: {
      code: '404',
      title: 'Page Not Found',
      desc: 'The emergency route you requested could not be found.',
      reportBtn: 'Report Emergency',
      homeBtn: 'Go to Home'
    }
  },
  hi: {
    nav: {
      tagline: 'आपातकालीन डिस्पैच',
      liveGrid: '24/7 लाइव अस्पताल ग्रिड सक्रिय',
      helpline: 'हेल्पलाइन 108',
      reportEmergency: 'आपातकाल रिपोर्ट करें',
      langLabel: 'भाषा',
      en: 'English (EN)',
      hi: 'हिन्दी (HI)',
      mr: 'मराठी (MR)'
    },
    home: {
      heroBadge: 'रियल-टाइम इमरजेंसी डिसीजन इंजन',
      heroTitle1: 'सही ',
      heroTitleRight: 'अस्पताल',
      heroTitle2: ' खोजें।',
      heroTitle3: 'सिर्फ ',
      heroTitleNearest: 'निकटतम',
      heroTitle4: ' नहीं।',
      heroDesc: 'हार्ट अटैक, स्ट्रोक या दुर्घटना जैसी गंभीर आपात स्थितियों में, निकटतम अस्पताल जाना व्यर्थ है यदि वहां आईसीयू बेड या विशेषज्ञ डॉक्टर उपलब्ध न हों। HLERS आपको तैयार डॉक्टरों और खाली बेड वाला सबसे तेज़ अस्पताल खोजकर देता है।',
      reportBtn: 'तुरंत आपातकाल रिपोर्ट करें',
      howItWorksBtn: 'यह कैसे काम करता है',
      speedVal: '< 30 से.',
      speedLbl: 'निर्णय गति',
      bedVal: 'लाइव',
      bedLbl: 'बेड ट्रैकिंग',
      trafficVal: '100%',
      trafficLbl: 'ट्रैफिक-जागरूक',
      simTitle: 'लाइव मल्टी-हॉस्पिटल रूटिंग',
      cardiac: 'हार्ट अटैक',
      stroke: 'स्ट्रोक / मस्तिष्क',
      trauma: 'दुर्घटना / चोट',
      burns: 'बर्न इमरजेंसी',
      yourLocation: 'आपका स्थान',
      cardiacName: 'हार्ट एवं आईसीयू सेंटर',
      strokeName: 'स्ट्रोक इमरजेंसी बे',
      traumaName: 'ट्रॉमा इमरजेंसी हब',
      burnsName: 'विशेष बर्न यूनिट',
      driveDuration: 'पहुंचने का समय',
      icuBeds: 'आईसीयू बेड',
      doctorStatus: 'डॉक्टर स्थिति',
      comparisonKicker: 'महत्वपूर्ण अंतर',
      comparisonHeading: 'आपातकाल में सामान्य मैप पर्याप्त क्यों नहीं हैं',
      comparisonSubtext: 'यह जाने बिना कि अस्पताल में बेड खाली हैं या नहीं, निकटतम इमारत में जाने से जानलेवा देरी होती है।',
      legacyStatus: 'सामान्य मैप ऐप्स',
      legacySub: 'केवल निकटतम स्थान',
      legacyTitle: '"निकटतम इमारत" की समस्या',
      legacyDesc: 'सामान्य मैप आपको केवल दूरी के आधार पर ले जाते हैं और अस्पताल की तैयारी के बारे में कुछ नहीं जानते।',
      drivingTime: 'ड्राइविंग समय:',
      legacyDrive: '4 मिनट (निकटतम)',
      legacyBeds: '0 बेड (अस्पताल भरा हुआ)',
      specialist: 'विशेषज्ञ:',
      legacySpec: 'डॉक्टर उपलब्ध नहीं',
      legacyOutcome: 'खतरा: मरीज को लौटा दिया जाता है और दूसरा अस्पताल ढूंढना पड़ता है (20+ मिनट बर्बाद)',
      legacyLi1: 'रवाना होने से पहले बेड क्षमता जांचने का कोई तरीका नहीं',
      legacyLi2: 'पहुंचने से पहले डॉक्टरों को कोई अलर्ट नहीं भेजा जाता',
      hlersStatus: 'HLERS इमरजेंसी सिस्टम',
      hlersSub: 'तैयार और सक्षम',
      hlersTitle: '"तैयार और सक्षम" समाधान',
      hlersDesc: 'ऐसा सबसे तेज़ अस्पताल ढूंढता है जहां वास्तव में आईसीयू बेड और विशेषज्ञ डॉक्टर ड्यूटी पर तैयार हों।',
      hlersDrive: '6 मिनट (लाइव ट्रैफिक)',
      hlersBeds: '4 खाली बेड की गारंटी',
      hlersSpec: 'डॉक्टर अलर्टेड एवं तैयार',
      hlersOutcome: 'परिणाम: शून्य समय बर्बाद किए पहुंचते ही तत्काल इलाज शुरू',
      hlersLi1: 'आपातकालीन कक्ष डेस्क पर सीधा प्री-अराइवल अलर्ट',
      hlersLi2: 'सीधे इमरजेंसी गेट तक लाइव टर्न-बाय-टर्न नेविगेशन',
      bentoKicker: 'हर आपातकाल में तीन सुरक्षा कवच',
      bentoHeading: 'HLERS आपका सर्वश्रेष्ठ अस्पताल कैसे चुनता है',
      bentoSubtext: 'किसी भी अस्पताल की सिफारिश करने से पहले हम वास्तविक समय में तीन जीवन-रक्षक कारकों की जांच करते हैं।',
      step1Tag: 'चरण 1 · ट्रैफिक नेविगेशन',
      step1Badge: 'लाइव मैप्स सिंक',
      step1Title: 'लाइव ट्रैफिक के साथ सबसे तेज़ रास्ता',
      step1Desc: 'लाइव गूगल मैप्स ट्रैफिक का उपयोग करके हर नजदीकी अस्पताल का सबसे तेज़ रास्ता निकालता है ताकि आप जाम से बच सकें।',
      step1Analysis: 'लाइव ट्रैफिक विश्लेषण:',
      step1Avoids: 'जाम से बचाता है',
      step1Instant: 'त्वरित रूटिंग',
      step2Tag: 'चरण 2 · बेड उपलब्धता',
      step2Badge: 'रियल-टाइम',
      step2Title: 'खाली आईसीयू बेड की गारंटी',
      step2Desc: 'रवाना होने से पहले उपलब्ध आईसीयू बेड और आपातकालीन उपकरणों की जांच करता है ताकि आप भरे अस्पताल न पहुंचें।',
      step2MeterHeader: 'इमरजेंसी आईसीयू क्षमता',
      step2Verified: 'सत्यापित खाली',
      step2MeterFooter1: '4 क्रिटिकल केयर बेड तैयार',
      step2MeterFooter2: 'उपलब्ध',
      step3Tag: 'चरण 3 · डॉक्टर तत्परता',
      step3Badge: 'ड्यूटी पर',
      step3Title: 'सुनिश्चित करता है कि सही डॉक्टर मौजूद हों',
      step3Desc: 'पुष्टि करता है कि हृदय रोग विशेषज्ञ, स्ट्रोक डॉक्टर या ट्रॉमा सर्जन सक्रिय रूप से ड्यूटी पर तैयार हैं।',
      docHeart: 'हृदय रोग विशेषज्ञ',
      docBrain: 'मस्तिष्क एवं स्ट्रोक डॉक्टर',
      docTrauma: 'ट्रॉमा सर्जन',
      docReady: 'तैयार',
      docOnDuty: 'ड्यूटी पर',
      footerBrandSub: 'हाइपरलोकल इमरजेंसी रूटिंग सिस्टम',
      footerMission: 'मरीजों को लाइव आईसीयू बेड और ड्यूटी पर मौजूद विशेषज्ञ डॉक्टरों वाले सक्षम अस्पतालों से जोड़ने वाला इंटेलिजेंट आपातकालीन नेटवर्क।',
      footerHubsOnline: 'सभी क्षेत्रीय अस्पताल हब ऑनलाइन',
      footerTriageHeading: 'आपातकालीन ट्रायज',
      footerHowItWorksHeading: 'यह कैसे काम करता है',
      footerHotlinesHeading: 'इमरजेंसी हेल्पलाइन',
      hotlineNational: 'राष्ट्रीय चिकित्सा आपातकाल',
      hotlinePolice: 'पुलिस आपातकाल',
      footerNotice: 'सूचना:',
      footerNoticeText: 'HLERS एक निर्णय सहायता प्रणाली है। तत्काल एम्बुलेंस सहायता के लिए हमेशा तुरंत 108 पर कॉल करें।',
      footerCopyright: '© HLERS. तत्काल आपातकालीन सहायता के लिए निर्मित।'
    },
    emergencyForm: {
      headerTitle: 'आपातकालीन ट्रायज डिस्पैच',
      headerSub: 'सत्यापित बेड और तैयार डॉक्टरों वाले अस्पतालों के लिए तत्काल आपातकालीन मूल्यांकन।',
      gpsLocating: 'जीपीएस निर्देशांक स्कैन हो रहे हैं...',
      gpsLocked: 'जीपीएस स्थान लॉक हुआ (सटीकता ±5 मी.)',
      step1Title: '1. मरीज की आपातकालीन स्थिति चुनें',
      step2Title: '2. गंभीरता का स्तर चुनें',
      step3Title: '3. मरीज के स्थान की पुष्टि करें',
      condCardiacTitle: 'हार्ट अटैक / हृदय रोग',
      condCardiacDesc: 'सीने में तेज दर्द, सांस फूलना, अचानक बेहोशी',
      condStrokeTitle: 'स्ट्रोक / मस्तिष्क आघात',
      condStrokeDesc: 'चेहरा झुकना, हाथ में कमजोरी, बोलने में कठिनाई',
      condTraumaTitle: 'गंभीर दुर्घटना / चोट',
      condTraumaDesc: 'गहरा आघात, भारी रक्तस्राव, फ्रैक्चर, वाहन दुर्घटना',
      condBurnsTitle: 'गंभीर जलन / बर्न',
      condBurnsDesc: 'थर्मल, रासायनिक या बिजली से जलने की चोटें',
      condGeneralTitle: 'सामान्य गंभीर आपातकाल',
      condGeneralDesc: 'अचेत अवस्था, सांस लेने में विफलता, गंभीर एलर्जी',
      sevCritical: 'अत्यंत गंभीर / जानलेवा',
      sevSevere: 'गंभीर / त्वरित',
      sevModerate: 'मध्यम / स्थिर',
      locPlaceholder: 'वर्तमान स्थान, लैंडमार्क या पता दर्ज करें',
      findBtn: 'सक्षम अस्पताल तुरंत खोजें',
      findingBtn: 'लाइव ट्रैफिक और आईसीयू बेड की गणना जारी...'
    },
    hospitalList: {
      triageTitle: 'आपातकालीन डिस्पैच परिणाम',
      triageSub: 'लाइव ट्रैफिक, सत्यापित आईसीयू बेड और विशेषज्ञ डॉक्टरों की तत्परता द्वारा रैंक किया गया।',
      sortFastest: 'सबसे कम यात्रा समय',
      sortBeds: 'सर्वाधिक खाली बेड',
      sortBest: 'सर्वोत्तम मेडिकल मैच',
      verifiedReady: 'सत्यापित तैयार',
      bedsAvailable: 'आईसीयू बेड उपलब्ध',
      specialistOnDuty: 'विशेषज्ञ डॉक्टर ड्यूटी पर',
      distanceAway: 'दूरी',
      directAlertBtn: 'इमरजेंसी रूम को प्री-अराइवल अलर्ट भेजें',
      alertSentBtn: 'अलर्ट अस्पताल डेस्क पर पहुंच गया',
      viewMap: 'रूट एवं लाइव गेट देखें',
      callDesk: 'इमरजेंसी डेस्क को कॉल करें'
    },
    alertConfirm: {
      alertSuccessTitle: 'आपातकालीन अलर्ट सफलतापूर्वक भेजा गया',
      alertSuccessSub: 'गंतव्य अस्पताल के आपातकालीन कक्ष को आपके आगमन की सूचना दे दी गई है।',
      etaLabel: 'अनुमानित आगमन समय',
      hospitalLabel: 'गंतव्य अस्पताल',
      conditionLabel: 'मरीज की स्थिति',
      bedStatusLabel: 'आरक्षित आईसीयू बेड',
      docStatusLabel: 'तैनात विशेषज्ञ डॉक्टर',
      checklistTitle: 'पहुंचने से पहले आवश्यक कदम',
      check1: 'मरीज को शांत रखें और अनावश्यक हलचल से बचें',
      check2: 'आपातकालीन वाहन के लिए रास्ता साफ रखें',
      check3: 'मरीज का पहचान पत्र और मेडिकल इतिहास तैयार रखें',
      check4: 'सीधे इमरजेंसी प्रवेश द्वार तक लाइव नेविगेशन का पालन करें',
      startNavBtn: 'लाइव जीपीएस टर्न-बाय-टर्न नेविगेशन शुरू करें',
      cancelAlertBtn: 'अलर्ट संशोधित / रद्द करें'
    },
    notFound: {
      code: '404',
      title: 'पृष्ठ नहीं मिला',
      desc: 'आपके द्वारा अनुरोधित आपातकालीन मार्ग उपलब्ध नहीं है।',
      reportBtn: 'आपातकाल रिपोर्ट करें',
      homeBtn: 'होम पेज पर जाएं'
    }
  },
  mr: {
    nav: {
      tagline: 'तातडीची मदत डिस्पॅच',
      liveGrid: '24/7 थेट रुग्णालय ग्रिड सक्रिय',
      helpline: 'हेल्पलाइन 108',
      reportEmergency: 'तातडीची मदत मागा',
      langLabel: 'भाषा',
      en: 'English (EN)',
      hi: 'हिन्दी (HI)',
      mr: 'मराठी (MR)'
    },
    home: {
      heroBadge: 'रिअल-टाइम आणीबाणी निर्णय इंजिन',
      heroTitle1: 'योग्य ',
      heroTitleRight: 'रुग्णालय',
      heroTitle2: ' शोधा.',
      heroTitle3: 'फक्त ',
      heroTitleNearest: 'जवळचे',
      heroTitle4: ' नाही.',
      heroDesc: 'हार्ट अटॅक, स्ट्रोक किंवा गंभीर अपघातात जवळच्या रुग्णालयात जाणे व्यर्थ ठरते जर तिथे आयसीयू बेड किंवा तज्ज्ञ डॉक्टर उपलब्ध नसतील. HLERS तुम्हाला तयार डॉक्टर आणि उपलब्ध बेड असलेले सर्वात वेगवान रुग्णालय शोधून देते.',
      reportBtn: 'आता तातडीची मदत मागा',
      howItWorksBtn: 'हे कसे कार्य करते',
      speedVal: '< 30 सेकंद',
      speedLbl: 'निर्णय गती',
      bedVal: 'थेट',
      bedLbl: 'बेड ट्रॅकिंग',
      trafficVal: '100%',
      trafficLbl: 'वाहतूक-सजग',
      simTitle: 'थेट मल्टि-हॉस्पिटल मार्गनिर्देशन',
      cardiac: 'हार्ट अटॅक',
      stroke: 'स्ट्रोक / मेंदू',
      trauma: 'अपघात / दुखापत',
      burns: 'भाजणे आणीबाणी',
      yourLocation: 'तुमचे स्थान',
      cardiacName: 'हृदयरोग व आयसीयू केंद्र',
      strokeName: 'स्ट्रोक इमर्जन्सी बे',
      traumaName: 'ट्रॉमा इमर्जन्सी हब',
      burnsName: 'विशेष बर्न युनिट',
      driveDuration: 'प्रवासाचा वेळ',
      icuBeds: 'आयसीयू बेड्स',
      doctorStatus: 'डॉक्टर स्थिती',
      comparisonKicker: 'महत्त्वाचा फरक',
      comparisonHeading: 'आणीबाणीत सामान्य नकाशे पुरेसे का नाहीत',
      comparisonSubtext: 'बेड उपलब्ध आहेत की नाही हे न जाणता जवळच्या इमारतीत धाव घेतल्याने जीवघेणा उशीर होतो.',
      legacyStatus: 'सामान्य नकाशा ॲप्स',
      legacySub: 'फक्त जवळचे ठिकाण',
      legacyTitle: '"जवळची इमारत" समस्या',
      legacyDesc: 'सामान्य नकाशे तुम्हाला फक्त अंतरावरून नेतात, त्यांना रुग्णालयाच्या सज्जतेबद्दल काहीही माहिती नसते.',
      drivingTime: 'प्रवासाचा वेळ:',
      legacyDrive: '4 मिनिटे (सर्वात जवळचे)',
      legacyBeds: '0 बेड्स (रुग्णालय पूर्ण भरलेले)',
      specialist: 'तज्ज्ञ डॉक्टर:',
      legacySpec: 'डॉक्टर उपलब्ध नाहीत',
      legacyOutcome: 'धोका: रुग्णाला परत पाठवले जाते आणि दुसरे रुग्णालय शोधावे लागते (20+ मिनिटे वाया)',
      legacyLi1: 'निघण्यापूर्वी बेड क्षमता तपासण्याची कोणतीही सोय नाही',
      legacyLi2: 'पोहोचण्यापूर्वी डॉक्टरांना कोणताही पूर्व-इशारा जात नाही',
      hlersStatus: 'HLERS आणीबाणी प्रणाली',
      hlersSub: 'सज्ज आणि सक्षम',
      hlersTitle: '"सज्ज आणि सक्षम" उपाय',
      hlersDesc: 'जिथे प्रत्यक्ष आयसीयू बेड आणि तज्ज्ञ डॉक्टर ड्युटीवर हजर आहेत असे सर्वात वेगवान रुग्णालय शोधते.',
      hlersDrive: '6 मिनिटे (थेट वाहतूक)',
      hlersBeds: '4 उपलब्ध बेड्सची खात्री',
      hlersSpec: 'डॉक्टर अलर्टेड आणि सज्ज',
      hlersOutcome: 'निकाल: वेळ वाया न घालवता पोहोचताच त्वरित उपचार सुरू',
      hlersLi1: 'इमर्जन्सी रूम डेस्कवर थेट पूर्व-सूचना अलर्ट',
      hlersLi2: 'थेट इमर्जन्सी गेटपर्यंत अचूक थेट दिशादर्शन',
      bentoKicker: 'प्रत्येक आणीबाणीत तीन सुरक्षा स्तर',
      bentoHeading: 'HLERS तुमचे सर्वोत्तम रुग्णालय कसे शोधते',
      bentoSubtext: 'कोणत्याही रुग्णालयाची शिफारस करण्यापूर्वी आम्ही रिअल-टाइममध्ये तीन जीवनरक्षक घटकांची पडताळणी करतो.',
      step1Tag: 'टप्पा 1 · वाहतूक मार्गनिर्देशन',
      step1Badge: 'थेट नकाशे सिंक',
      step1Title: 'थेट वाहतुकीनुसार सर्वात वेगवान मार्ग',
      step1Desc: 'गुगल मॅप्सच्या थेट वाहतुकीचा वापर करून जवळच्या प्रत्येक रुग्णालयाचा वेगवान मार्ग शोधते जेणेकरून वाहतूक कोंडी टाळता येईल.',
      step1Analysis: 'थेट वाहतूक विश्लेषण:',
      step1Avoids: 'कोंडी टाळते',
      step1Instant: 'त्वरित मार्ग',
      step2Tag: 'टप्पा 2 · बेड उपलब्धता',
      step2Badge: 'रिअल-टाइम',
      step2Title: 'उपलब्ध आयसीयू बेड्सची खात्री',
      step2Desc: 'निघण्यापूर्वी उपलब्ध आयसीयू बेड्स आणि उपकरणांची खात्री करते जेणेकरून पूर्ण भरलेल्या रुग्णालयात जाणे टळेल.',
      step2MeterHeader: 'इमर्जन्सी आयसीयू क्षमता',
      step2Verified: 'सत्यापित उपलब्ध',
      step2MeterFooter1: '4 क्रिटिकल केअर बेड्स सज्ज',
      step2MeterFooter2: 'उपलब्ध',
      step3Tag: 'टप्पा 3 · डॉक्टर तत्परता',
      step3Badge: 'ड्युटीवर',
      step3Title: 'योग्य डॉक्टर हजर असल्याची खात्री',
      step3Desc: 'हृदयरोगतज्ज्ञ, स्ट्रोक डॉक्टर किंवा ट्रॉमा सर्जन प्रत्यक्ष ड्युटीवर सज्ज असल्याची पडताळणी करते.',
      docHeart: 'हृदयरोगतज्ज्ञ',
      docBrain: 'मेंदू व स्ट्रोक डॉक्टर',
      docTrauma: 'ट्रॉमा सर्जन',
      docReady: 'सज्ज',
      docOnDuty: 'ड्युटीवर',
      footerBrandSub: 'हायपरलोकल इमर्जन्सी रूटिंग सिस्टीम',
      footerMission: 'रुग्णांना थेट उपलब्ध आयसीयू बेड्स आणि ड्युटीवरील तज्ज्ञ डॉक्टरांशी जोडणारे बुद्धिमान आणीबाणी नेटवर्क.',
      footerHubsOnline: 'सर्व प्रादेशिक रुग्णालय हब्स ऑनलाइन',
      footerTriageHeading: 'आणीबाणी ट्रायज',
      footerHowItWorksHeading: 'हे कसे कार्य करते',
      footerHotlinesHeading: 'आपत्कालीन हेल्पलाइन',
      hotlineNational: 'राष्ट्रीय वैद्यकीय आणीबाणी',
      hotlinePolice: 'पोलीस आणीबाणी',
      footerNotice: 'सूचना:',
      footerNoticeText: 'HLERS ही निर्णय साहाय्य प्रणाली आहे. तात्काळ रुग्णवाहिका मदतीसाठी नेहमी त्वरित 108 वर कॉल करा.',
      footerCopyright: '© HLERS. तात्काळ आणीबाणी मदतीसाठी निर्मित.'
    },
    emergencyForm: {
      headerTitle: 'आणीबाणी ट्रायज डिस्पॅच',
      headerSub: 'सत्यापित बेड्स आणि सज्ज डॉक्टरांसह रुग्णालयांकडे त्वरित रुग्ण मार्गनिर्देशन.',
      gpsLocating: 'जीपीएस निर्देशांक तपासत आहे...',
      gpsLocked: 'जीपीएस स्थान लॉक झाले (अचूकता ±5 मी.)',
      step1Title: '1. रुग्णाची आणीबाणी स्थिती निवडा',
      step2Title: '2. तीव्रतेची पातळी निवडा',
      step3Title: '3. रुग्णाच्या स्थानाची खात्री करा',
      condCardiacTitle: 'हार्ट अटॅक / हृदयरोग',
      condCardiacDesc: 'छातीत तीव्र वेदना, श्वास घेण्यास त्रास, अचानक बेशुद्ध पडणे',
      condStrokeTitle: 'स्ट्रोक / मेंदूचा झटका',
      condStrokeDesc: 'चेहरा वाकडा होणे, हातामध्ये अशक्तपणा, बोलताना अडखळणे',
      condTraumaTitle: 'गंभीर अपघात / दुखापत',
      condTraumaDesc: 'गंभीर जखम, अतिरक्तस्राव, हाड मोडणे, वाहन अपघात',
      condBurnsTitle: 'गंभीरपणे भाजणे',
      condBurnsDesc: 'उष्णता, रासायनिक किंवा विजेच्या धक्क्याने भाजणे',
      condGeneralTitle: 'सामान्य गंभीर आणीबाणी',
      condGeneralDesc: 'बेशुद्धावस्था, श्वास बंद पडणे, तीव्र ॲलर्जी',
      sevCritical: 'अत्यंत गंभीर / जीवघेणी',
      sevSevere: 'गंभीर / तातडीची',
      sevModerate: 'मध्यम / स्थिर',
      locPlaceholder: 'सध्याचे स्थान, लँडमार्क किंवा पत्ता प्रविष्ट करा',
      findBtn: 'सक्षम रुग्णालय त्वरित शोधा',
      findingBtn: 'थेट वाहतूक आणि आयसीयू बेड्स तपासत आहे...'
    },
    hospitalList: {
      triageTitle: 'आणीबाणी डिस्पॅच निकाल',
      triageSub: 'थेट वाहतूक, उपलब्ध आयसीयू बेड्स आणि तज्ज्ञ डॉक्टरांच्या सज्जतेनुसार क्रमवारी.',
      sortFastest: 'कमीत कमी प्रवासाचा वेळ',
      sortBeds: 'सर्वाधिक उपलब्ध बेड्स',
      sortBest: 'सर्वोत्कृष्ट वैद्यकीय मॅच',
      verifiedReady: 'सत्यापित सज्ज',
      bedsAvailable: 'आयसीयू बेड्स उपलब्ध',
      specialistOnDuty: 'तज्ज्ञ डॉक्टर ड्युटीवर',
      distanceAway: 'अंतर',
      directAlertBtn: 'इमर्जन्सी रूमला पूर्व-सूचना पाठवा',
      alertSentBtn: 'अलर्ट हॉस्पिटल डेस्कला पोहोचला',
      viewMap: 'मार्ग आणि थेट गेट्स पहा',
      callDesk: 'इमर्जन्सी डेस्कला कॉल करा'
    },
    alertConfirm: {
      alertSuccessTitle: 'आणीबाणी अलर्ट यशस्वीरीत्या पाठवला',
      alertSuccessSub: 'गंतव्य रुग्णालयातील आपत्कालीन कक्षाला तुमच्या आगमनाची पूर्व-सूचना देण्यात आली आहे.',
      etaLabel: 'अंदाजे पोहोचण्याची वेळ',
      hospitalLabel: 'गंतव्य रुग्णालय',
      conditionLabel: 'रुग्णाची स्थिती',
      bedStatusLabel: 'राखीव आयसीयू बेड',
      docStatusLabel: 'नेमलेले तज्ज्ञ डॉक्टर',
      checklistTitle: 'पोहोचण्यापूर्वी आवश्यक कृती',
      check1: 'रुग्णाला शांत ठेवा आणि हालचाल टाळा',
      check2: 'रुग्णवाहिकेसाठी रस्ता मोकळा ठेवा',
      check3: 'रुग्णाचे ओळखपत्र आणि वैद्यकीय माहिती तयार ठेवा',
      check4: 'थेट इमर्जन्सी प्रवेशद्वारापर्यंतच्या थेट दिशादर्शनाचे पालन करा',
      startNavBtn: 'थेट जीपीएस नेव्हिगेशन सुरू करा',
      cancelAlertBtn: 'अलर्ट सुधारा / रद्द करा'
    },
    notFound: {
      code: '404',
      title: 'पृष्ठ सापडले नाही',
      desc: 'तुम्ही शोधत असलेला आणीबाणी मार्ग उपलब्ध नाही.',
      reportBtn: 'तातडीची मदत मागा',
      homeBtn: 'मुख्य पृष्ठावर जा'
    }
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('hlers_lang')
    return saved === 'hi' || saved === 'mr' ? saved : 'en'
  })

  useEffect(() => {
    localStorage.setItem('hlers_lang', language)
  }, [language])

  const t = (path) => {
    const keys = path.split('.')
    let current = translations[language] || translations.en
    for (const key of keys) {
      if (current && current[key] !== undefined) {
        current = current[key]
      } else {
        let fallback = translations.en
        for (const fKey of keys) {
          if (fallback && fallback[fKey] !== undefined) {
            fallback = fallback[fKey]
          } else {
            return path
          }
        }
        return fallback
      }
    }
    return current
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
